[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/prover",
]
exclude = [
    "projects/book",
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
