[package]
name = "bootstrap"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"

[dependencies.yggdrasil-shared]
version = "0.2.*"
path = '../ygg-core'

[features]
default = []

