[package]
name = "bootstrap"
publish = false
version = "0.0.0"
edition = "2021"

[dependencies]
num = "0.4.1"
serde = { version = "1.0.193", features = ["derive"] }
anyhow = "1.0.75"

[features]
default = []

